#!/bin/sh
#set -x
# helps bootstrapping am-utils, when checked out from CVS
# requires GNU autoconf and GNU automake
# this is not meant to go into the distributions
# Erez Zadok <ezk@cs.columbia.edu>

# test cwd
test -f ../amd/amd.c && cd ..
if [ ! -f amd/amd.c ]; then
    echo "Must run $0 from the top level source directory."
    exit 1
fi

# validate macros directory and some macro files
if [ ! -d m4/macros ]; then
    echo No m4/macros directory found!
    exit 1
fi
if [ ! -f m4/macros/HEADER ]; then
    echo No m4/macros/HEADER file found!
    exit 1
fi

# remove any remaining autom4te.cache directory
rm -fr autom4te.cache autom4te-*.cache

# generate acinclude.m4 file
echo "AMU: prepare acinclude.m4..."
test -f acinclude.m4 && mv -f acinclude.m4 acinclude.m4.old
(cd m4/macros
 for i in HEADER *.m4; do
     cat $i
     echo
     echo
 done
 cat TRAILER
) > acinclude.m4

# generate the rest of the scripts
echo "AMU: autoreconf..."
# show version
autoreconf --version 2>&1 | head -1
if autoreconf -f -i; then
    :
else
    echo "autoreconf command failed.  fix errors and rerun $0."
    exit 2
fi

echo "AMU: Fixing ylwrap..."
patch << \EOF
--- ylwrap.orig	2013-05-14 20:00:39.000000000 -0400
+++ ylwrap	2013-05-14 20:06:06.000000000 -0400
@@ -199,8 +199,24 @@
       # include guards too.
       FROM=`guard "$from"`
       TARGET=`guard "$to"`
+
+      prefix=`echo $input | sed \
+		-e 's,^.*/,,g' \
+		-e 's/_parse.[yl]$/_/g' \
+		-e 's/_tok.[yl]$/_/g'`
+
+      case $prefix in
+      *.y)
+	      code_prefix="$(basename $prefix _gram.y)_yy";;
+      *.l)
+	      code_prefix="$(basename $prefix _lex.l)_yy";;
+      *)
+	      code_prefix="$prefix";;
+      esac
+
       sed -e "/^#/!b" -e "s|$input_rx|$input_sub_rx|" -e "$rename_sed" \
-          -e "s|$FROM|$TARGET|" "$from" >"$target" || ret=$?
+          -e "s|$FROM|$TARGET|" "$from" | sed -e "s|yy|$code_prefix|g" > \
+	  "$target" || ret=$?
 
       # Check whether files must be updated.
       if test "$from" != "$parser"; then
\EOF

# save timestamp
echo "AMU: save timestamp..."
echo timestamp > stamp-h.in

exit 0
